// Impacchetta @formatjs/icu-messageformat-parser (devDependency) in lib/dist/icuParser.js:
// un unico chunk ESM minificato, con il banner di licenza MIT. Generato da npm run build,
// non versionato (sta sotto lib/dist, già in .gitignore) — il job "publish" lo scarica come
// artefatto separato (vedi .github/workflows/publish.yml), perché "il resto di lib/ è
// sorgente versionato".
//
// Stesso schema API di test/measureReactBundle.mjs (rolldown via API JS).

import { rolldown } from "rolldown";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FILE = join(ROOT, "lib/dist/icuParser.js");

async function main() {
  const bundle = await rolldown({ input: join(ROOT, "test/vendorIcuEntry.mjs") });
  const { output } = await bundle.generate({ format: "esm", minify: true });
  await bundle.close();

  const chunks = output.filter((o) => o.type === "chunk");
  if (chunks.length !== 1) {
    throw new Error(`vendorIcu.mjs: expected exactly one chunk, got ${chunks.length}`);
  }
  const code = chunks[0].code;

  const parserVersion = JSON.parse(
    readFileSync(join(ROOT, "node_modules/@formatjs/icu-messageformat-parser/package.json"), "utf8")
  ).version;
  const skeletonVersion = JSON.parse(
    readFileSync(join(ROOT, "node_modules/@formatjs/icu-skeleton-parser/package.json"), "utf8")
  ).version;
  const license = readFileSync(join(ROOT, "node_modules/@formatjs/icu-messageformat-parser/LICENSE.md"), "utf8");
  const licenseLines = license.split("\n").map((l) => ` *  ${l}`).join("\n");

  const banner = `/*! @formatjs/icu-messageformat-parser ${parserVersion} + @formatjs/icu-skeleton-parser ${skeletonVersion}
 *  Generated by test/vendorIcu.mjs from viteTranslate's devDependencies — do not edit, \`npm run build\` rewrites it.
${licenseLines}
 */
`;

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, banner + code + `export const FORMATJS_PARSER_VERSION = ${JSON.stringify(parserVersion)};\n`);

  const mod = await import(pathToFileURL(OUT_FILE).href + "?t=" + Date.now());
  const parsed = mod.parse("{0}", { ignoreTag: true });
  if (parsed[0]?.type !== 1) {
    console.error("vendorIcu.mjs: sanity check failed — parse(\"{0}\") did not produce an argument node");
    process.exitCode = 1;
    return;
  }
  console.log(`vendorIcu.mjs: wrote lib/dist/icuParser.js (${parserVersion} + ${skeletonVersion})`);
}

await main();
